server:
  port: 10016
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.27.77:8848
    sentinel:
      transport:
        port: 10003
        dashboard: 182.61.27.77:8858
  zipkin:
    base-url: http://zipkin.stalary.com
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://182.61.27.77:3306/personfilter?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: personfilter
    password: root # 自行修改一下密码
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1 # 最小空闲连接数
      maximum-pool-size: 15 # 最大连接数量
      pool-name: user-pool
      connection-test-query: SELECT 1 # 测试连接
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
logging:
  level:
    com.stalary.pf.recruit.client: DEBUG # feign日志
rocketmq:
  producer:
    group: recruit
  name-server: 180.76.116.132:9876

