server:
  debug: false
  port: 10015
  max-http-header-size: 8192
  user: 192.168.0.106:7100
spring:
  data:
    elasticsearch:
      cluster-nodes: 180.76.116.132:9300
      cluster-name: elasticsearch # 使用docker启动的默认集群名称
      properties:
        transport:
          tcp:
            connect_timeout: 2s
  datasource:
    url: jdbc:mysql://182.61.27.77:3306/personfilter?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: personfilter
    password: root # 自行修改一下密码
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1 # 最小空闲连接数
      maximum-pool-size: 15 # 最大连接数量
      pool-name: user-pool
      connection-test-query: SELECT 1 # 测试连接
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.27.77:8848
    sentinel:
      transport:
        port: 10003
        dashboard: 182.61.27.77:8858
  zipkin:
    base-url: http://zipkin.stalary.com
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.user.client: DEBUG # feign日志