server:
  port: 10012
  max-http-header-size: 8192
spring:
  redis:
    host: 182.61.27.77
    timeout: 5000ms
    port: 6379
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 1
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.27.77:8848
    sentinel:
      transport:
        port: 10003
        dashboard: 182.61.27.77:8858
  zipkin:
    base-url: http://zipkin.stalary.com
  sleuth:
    sampler:
      probability: 1.0
  mail:
    # 邮箱服务器地址，这里使用的是163.com的邮件服务器
    host: smtp.163.com
    # 在163.com注册的用户名，注意这里不需要@163.com后缀
    username: zhuaizhazha@163.com
    # 在163.com使用的授权码(关闭授权码时使用密码)，需要开启POP3/SMTP服务
    password: ARNTJROKMRDJWKMF
    port: 465
    default-encoding: UTF-8
logging:
  level:
    com.stalary.pf.outside.client: DEBUG # feign日志