server:
  port: 10014
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.27.77:8848
  zipkin:
    base-url: http://zipkin.stalary.com
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.consumer.client: DEBUG # feign日志
rocketmq:
  name-server: 180.76.116.132:9876